language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
os:
  - windows
  - linux
  - osx
install:
  - pip install -U pytest pytest-cov coveralls
  - pip install -e .
script:
  - pytest
after_success:
  - coveralls
